### ISSUE TITLE
Allow full control of variables

### ISSUE THREAD

**Issue by astrauka** [vinted/interactor-initializer#2]
What if we provided the same expression level as ones has in `def initialize(...)`.

Example:

``` ruby
def initialize(name, body = 'Empty', status:, options: {})
```

Could be defined via

``` ruby
initialize_with "name, body = 'Empty', status:, options: {}"
```

So the interface would be that you have to write a string that contains exactly same expression as you would write in `initialize` definition.

Steps:
- `eval` the string in the `initialize` definition
- parse the string splitting by `,` and removing everything that's not variable name to get attributes
- use the attributes to build boilerplate

Challenge there is when initialize with has a default variable which contains `,`

``` ruby
initialize_with "name, body = 'Empty', status:, options: { validate: false, debug: true }"
```

For this case parsing fails, but we can accept splat array of strings instead

``` ruby
initialize_with :name, "body = 'Empty'", 'status:', 'options: { validate: false, debug: true }'"
```

This is not nice syntax but it solves the problem in a structural way.
We also persist the ability to define the initializer via

``` ruby
initialize_with :name, :body
```

as this is same as `initialize_with([:name, :body])` as symbols can be converted to strings

@tomasv @ksarunas @titas @raimondasv @laurynas what are your thoughts?

**Comment by laurynas** [comment]
I agree that it would add flexibility and would easy migration of existing interactors, but I don't like `eval` option.. I have bad feeling about code in strings :)

**Comment by ksarunas** [comment]
Actually I had the same idea, and yes it can only be achieved by passing a string.. Thus, I did not like it. It is ugly.

I would rather go with sth like:

``` ruby
initialize_with :user, :body, :system
param :system, default: -> { false }
```

Or for optional cases:

``` ruby
initialize_with :user, :body, :options
param :options, required: false
```

**Comment by tomasv** [comment]
String eval - 👎 . It's just too cryptic, and syntax highlighting won't work.

I can't think of an option that wouldn't be hard to read and simple to use at the same time. :)

**Comment by astrauka** [comment]
```
initialize_with :user, :body, :system
param :system, default: -> { false }
```

might become quite rich DSL which is not cool, on the other hand if we make the DSL intuitive, then it's ok.

```
initialize_with(
  :item, 
  user: { default: false }, 
  body: { keyword: true }, 
  system: { keyword: true, default: {} }
)
```

`item` is argument with no default value,
`user` is argument with default value,
`body` is a keyword argument with no default value, so it's required,
`system` is a keyword argument with default value.
@tomasv @ksarunas @laurynas what do you think?

**Comment by tomasv** [comment]
I don't think it's worth it. We're reinventing the wheel - Ruby itself - here.
